config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  resources :books, only: [:new, :index, :show, :create, :edit, :update, :destroy
  ]
  resources :users
  get "/home/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, length: { in: 1..200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, length: { in: 2..20 }, uniqueness: true
         validates :introduction, length: { maximum: 50 }

         has_many :books, dependent: :destroy
         has_one_attached :profile_image

def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top, :about]

   add_flash_types :success, :info, :warning, :danger

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)

    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "successfully create new book"
      redirect_to book_path(@book[:id])
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)

    if @user != current_user
      redirect_to books_path
    else
      render :layout => 'home_layout'
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully update"
      redirect_to book_path(@book)
    else
      @user = current_user
      render :edit, :layout => 'home_layout'

    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "successfully deleat"
    redirect_to books_path
  end


  private

  def book_params

    params.require(:book).permit(:title, :body)

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
    render :layout => 'home_layout'
  end

  def top
    render :layout => 'home_layout'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id])
  end

  def edit
    @user = User.find(params[:id])

    if @user == current_user
       render :layout => 'home_layout'
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "successfully update"
      redirect_to user_path(current_user.id)
    else
      render :edit, :layout => 'home_layout'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
 <div class="container container-md-10 offset-md-3">

    <h2>Editing Book</h2>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>


    <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

      <h2>Title</h2>
      <%= f.text_field :title %>

      <h2>Body</h2>
      <%= f.text_area :body %>

      <%= f.submit 'Update Book' %>
    <% end %>

    <table role="presentation" >
      <tr>
        <th><%= link_to "Show", book_path(@book.id) %></th>
        <th><p>|</p></th>
        <th><%= link_to "Back", books_path %></th>
      </tr>
    </table>
  </div>

app/views/books/index.html.erb
<!--book一覧-->

 <table class="table container-md-10 offset-md-1">
    <div class = "row">
      <div class = "col" ><h2>Books</h2></div>
    </div>
  <thead class="row border-top border-2">
    <th class="col mx-1"><p></p></th>
    <th class="col mx-1"><p>Title</p></th>
    <th class="col mx-1"><p>Opinion</p></th>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr class="row border-top border-3">
        <td class="col mx-1">
          <%= link_to user_path(book.user.id) do%>
          <%= image_tag book.user.get_profile_image(100,100)  %>
          <%end%>
        </td>
        <td class="col mx-1"><%= link_to book.title, book_path(book.id) %></td>
        <td class="col mx-1"><%= book.body %></td>
      </tr>
     <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>


<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<!--BOOK詳細ページ-->
<table class=" table container-md-10 offset-md-1">
    <thead>
      <tr>
        <th class = "col" ><h2>Book detail</h2></th>
        <th class = "col"></th>
        <th class = "col"></th>
        <th class = "col"></th>
        <th class = "col-md-8"></th>
      </tr>
    </thead>
    <tbody>
      <tr class="row no-gutters border-top border-3">

          <td class="col mx-1 ">
            <%= link_to user_path(@book.user.id) do%>
            <%= image_tag @book.user.get_profile_image(100,100)  %>
            <%= link_to @book.user.name, user_path(@book.user.id) %>
            <%end%>
          </td>
          <td class="col mx-1"><%= link_to @book.title, book_path(@book.id) %></td>
          <td class="col mx-1"><%= @book.body %></td>
          <% if @user == current_user %>
            <td class="col mx-1">
              <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-secondary m-2 btn-success" %>
            </td>
            <td class="col mx-1">
              <%= link_to "Destroy", book_path(@book.id),class: "btn btn-secondary m-2 btn-danger", method: :delete, "data-confirm" => "Are you sure?" %>
            </td>
          <% else %>
          <% end %>

      </tr>
    </tbody>
  </table>

app/views/homes/about.html.erb
<div class = "col-lg-12 text-center" >
  <h1>Welcome to</h1>
  <%= icon('fas','book')%>
  <h1>Bookers!!</h1>
</div>

app/views/homes/top.html.erb
<div class = "col-lg-12 text-center" >
  <h1>Welcome to Bookers!!</h1>
  <%= icon('fas','book')%>
  <p>In <%= icon('fas','book')%> Bookers,</p>
  <p>you can share and exchange your opinions,inpression,and emotions</p>

  <p>about various books!</p>

  <%= link_to 'Log in', user_session_path, class: "btn btn-secondary col-6 m-2 btn-info" %>
  <%= link_to 'Sign up', new_user_session_path, class: "btn btn-secondary col-6  btn-success" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100 ">
      <header class="shadow-sm">
        <nav class="navbar navbar-expand-lg navbar-light bg-dark">
          <div class="container">
            <a class="navbar-brand p-3 text-white" href="/">Bookers</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto m-3 ">
              <<% if user_signed_in? %>
                <li class = "m-1 text-white">
                  <%= link_to icon('fas','home', 'Home'), user_path(current_user.id) %>
                </li>
                <li class = "m-1 text-white">
                  <%= link_to icon('fas','users','Users'), users_path %>
                </li>

                <li class = "m-1 text-white">
                  <%= link_to icon('fas','book-open','Books'), books_path %>
                </li>
                <li class = "m-1 text-white">
                  <%= link_to icon('fas','sign-out-alt','Log out'), destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
                <li class = "m-1 text-white">
                  <%= link_to icon('fas','home','Home'), root_path %>
                </li>
                <li class = "m-1 text-white">
                  <%= link_to icon('fas','link','About'), about_path %>
                </li>
                <li class = "m-1 text-white">
                  <%= link_to icon('fas','user-plus','Sign up'), new_user_registration_path %>
                </li>
                <li class = "m-1 text-white">
                  <%= link_to icon('fas','sign-in-alt','Log in'), user_registration_path %>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>


      <div class = "row">
          <main class="col-md-8 offset-md-1">
            <p class="notice"><%= notice %></p>
          <%= yield %>
          </main>
      </div>


      <footer class="container">
        <div class="row">
          <div class="col text-center center-block">

            <p>CopyRight Infratop.inc</p>

          </div>
        </div>
      </footer>
    </body>


</html>

app/views/users/edit.html.erb
<h2>Editing User</h2>

<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "Profile Image", accept: "image/*" %>
  <h4>Introduction</h4>
  <%= f.text_field :introduction %>
  <br>
  <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<!--user一覧-->

<table class="table container offset-md-1">
  <div class = "row">
    <div class = "col-md-8" ><h2>Users</h2></div>
  </div>
  <thead>
    <tr class="row border-top border-3">
      <th class="col "><p>Image</p></th>
      <th class="col "><p>Name</p></th>
      <th class="col "><p></p></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="row no-gutters border-top border-3">
        <td class="col"><%= image_tag user.get_profile_image(100,100) %></td>
        <td class="col"><%= user.name %></td>
        <td class="col"><%= link_to "Show", user_path(user.id) %></td>
      </tr>
     <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<!--ユーザー詳細ページ-->


  <table class="table container container-md-10 offset-md-1">
    <div class = "col" ><h2>Books</h2></div>
    <thead>
      <tr class="row no-gutters border-top border-3">
        <th class="col p-3"><p></p></th>
        <th class="col p-3"><p>Title</p></th>
        <th class="col p-3"><p>Opinion</p></th>
      </tr>
    </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr class="row no-gutters border-top border-3">
            <td class="col p-3">
              <%= link_to user_path(book.user.id) do%>
              <%= image_tag book.user.get_profile_image(100,100)  %>
              <%end%>
            </td>
            <td class="col p-3"><%= link_to book.title, book_path(book.id) %></td>
            <td class="col p-3"><%= book.body %></td>
          </tr>
         <% end %>
      </tbody>
  </table>